# Generated by Django 6.0.1 on 2026-05-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название уровня')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Номер лота')),
                ('volume', models.PositiveIntegerField(verbose_name='Объем (мкл)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Уровень аликвоты',
                'verbose_name_plural': 'Уровни аликвот',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AliquotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон аликвоты',
                'verbose_name_plural': 'Шаблоны аликвот',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AliquotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_data', models.JSONField(default=dict, verbose_name='Данные уровней')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время печати')),
                ('printed_by', models.CharField(blank=True, max_length=100, verbose_name='Кто печатал')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aliquotes.aliquottemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'История печати',
                'verbose_name_plural': 'История печати',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество этикеток')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliquotes.aliquotlevel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliquotes.aliquottemplate')),
            ],
            options={
                'unique_together': {('template', 'level')},
            },
        ),
        migrations.AddField(
            model_name='aliquottemplate',
            name='levels',
            field=models.ManyToManyField(through='aliquotes.TemplateLevel', to='aliquotes.aliquotlevel', verbose_name='Уровни'),
        ),
    ]
