# Generated by Django 6.0.1 on 2026-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='кастомная этикетка')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='описание')),
                ('type_labels', models.CharField(choices=[('barcode', 'Штрих-код'), ('text', 'Текст')], default='text')),
            ],
        ),
    ]
