# Generated by Django 6.0.1 on 2026-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlabel',
            name='barcode',
            field=models.CharField(default=1, unique=True, verbose_name='Штрихкод'),
            preserve_default=False,
        ),
    ]
