# Generated by Django 6.0.1 on 2026-01-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код линии')),
                ('name', models.CharField(max_length=50, verbose_name='Название линии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Линия анализатора',
                'verbose_name_plural': 'Линии анализатора',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код теста')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('test_type', models.CharField(max_length=20, verbose_name='Тип теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sample_type', models.CharField(default='Сыворотка', max_length=50, verbose_name='Тип пробы')),
                ('processing_time', models.PositiveIntegerField(default=18, verbose_name='Время выполнения (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Лабораторный тест',
                'verbose_name_plural': 'Лабораторные тесты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TestLineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная линия')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет (1-высший)')),
                ('max_daily_capacity', models.PositiveIntegerField(default=100, verbose_name='Макс. количество в день')),
                ('reagent_consumption', models.FloatField(default=1.0, verbose_name='Расход реагента (мл)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_configurations', to='teachbase.analyzerline')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_configurations', to='teachbase.laboratorytest')),
            ],
            options={
                'verbose_name': 'Конфигурация тест-линия',
                'verbose_name_plural': 'Конфигурации тест-линия',
                'ordering': ['priority', 'line__code'],
                'unique_together': {('test', 'line')},
            },
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='analyzer_lines',
            field=models.ManyToManyField(related_name='tests', through='teachbase.TestLineConfiguration', to='teachbase.analyzerline', verbose_name='Линии анализатора'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['code'], name='teachbase_l_code_c9de16_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['test_type'], name='teachbase_l_test_ty_63850b_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['is_active'], name='teachbase_l_is_acti_5c5e7e_idx'),
        ),
    ]
