# Generated by Django 6.0.1 on 2026-04-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название реагента')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код реагента')),
                ('short_name', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('category', models.CharField(choices=[('hormones', 'Гормоны'), ('oncomarkers', 'Онкомаркеры'), ('autoimmune', 'Аутоиммунные'), ('vitamins', 'Витамины'), ('special', 'Специальные'), ('biochemistry', 'Биохимия')], max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Реагент',
                'verbose_name_plural': 'Реагенты',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RocheAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Roche Cobas 8000', max_length=200, verbose_name='Название')),
                ('code', models.CharField(default='ROCHE_C8000', max_length=50, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Анализатор Roche',
                'verbose_name_plural': 'Анализаторы Roche',
            },
        ),
        migrations.CreateModel(
            name='RocheModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('e801', 'E801 - Иммунохимический модуль'), ('e601', 'E601 - Иммунохимический модуль'), ('c702', 'C702 - Биохимический модуль')], max_length=10, verbose_name='Тип модуля')),
                ('module_number', models.PositiveSmallIntegerField(verbose_name='Номер модуля')),
                ('name', models.CharField(max_length=100, verbose_name='Название модуля')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='teachbase.rocheanalyzer', verbose_name='Анализатор')),
            ],
            options={
                'verbose_name': 'Модуль Roche',
                'verbose_name_plural': 'Модули Roche',
                'ordering': ['position', 'module_number'],
                'unique_together': {('analyzer', 'module_number')},
            },
        ),
        migrations.CreateModel(
            name='ModuleReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('CH1', 'Канал 1'), ('CH2', 'Канал 2')], max_length=3, null=True, verbose_name='Канал (только для e801/e601)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='teachbase.reagent', verbose_name='Реагент')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='teachbase.rochemodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Реагент в модуле',
                'verbose_name_plural': 'Реагенты в модулях',
                'unique_together': {('module', 'reagent')},
            },
        ),
    ]
