# Generated by Django 6.0.1 on 2026-04-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachbase', '0002_reagent_rocheanalyzer_rochemodule_modulereagent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulereagent',
            options={},
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='channel',
            field=models.CharField(blank=True, choices=[('CH1', 'Канал 1'), ('CH2', 'Канал 2')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='teachbase.rochemodule'),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='teachbase.reagent'),
        ),
    ]
