# Generated by Django 6.0.1 on 2026-04-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachbase', '0003_alter_modulereagent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulereagent',
            unique_together={('module', 'reagent', 'channel')},
        ),
    ]
