# Generated by Django 6.0.1 on 2026-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachbase', '0004_alter_modulereagent_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulereagent',
            options={'verbose_name': 'Реагент в модуле', 'verbose_name_plural': 'Реагенты в модулях'},
        ),
        migrations.AlterUniqueTogether(
            name='modulereagent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='channel',
            field=models.CharField(blank=True, choices=[('CH1', 'Канал 1'), ('CH2', 'Канал 2'), ('BOTH', 'Оба канала')], max_length=4, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='teachbase.rochemodule', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='modulereagent',
            name='reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='teachbase.reagent', verbose_name='Реагент'),
        ),
        migrations.AlterUniqueTogether(
            name='modulereagent',
            unique_together={('module', 'reagent')},
        ),
    ]
